[[redirects]]
  from = "/feed.xml"
  to = "https://lukebouch.blog/feed.xml"
  status = 301
  force = true

[[redirects]]
  from = "/feed.json"
  to = "https://lukebouch.blog/feed.json"
  status = 301
  force = true

[[redirects]]
  from = "/posts"
  to = "https://lukebouch.blog"
  status = 301
  force = true

[[redirects]]
  from = "/posts/*"
  to = "https://lukebouch.blog/:splat"
  status = 301
  force = true
