backend:
    name: github
    repo: 'lukebouch/lukebouch.com'
    branch: main

media_folder: static/img
public_folder: /img

collections:
    - name: 'projects'
      label: 'Projects'
      folder: 'content/projects'
      format: 'frontmatter'
      create: true
      slug: '{{slug}}'
      editor:
          preview: false
      fields:
          - { label: 'Name', name: 'name', widget: 'string' }
          - {
                label: 'Start Date',
                name: 'start_date',
                widget: 'datetime',
                required: false,
            }
          - {
                label: 'End Date',
                name: 'end_date',
                widget: 'datetime',
                required: false,
            }
          - {
                label: 'Description',
                name: 'description',
                widget: 'string',
                required: false,
            }
          - { label: 'Body', name: 'body', widget: 'markdown', required: false }
