backend:
  name: github
  repo: lukebouch/lukebouch.com

media_folder: static/img
public_folder: /images

collections:
  - name: 'projects'
    label: 'Projects'
    folder: 'content/projects'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Start Date', name: 'start_date', widget: 'datetime' }
      - { label: 'End Date', name: 'end_date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }